/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(insert_idle_frame.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0e7afc6ac0a9ea03924f8d35edbe2884)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ccsds/insert_idle_frame.h>
// pydoc.h is automatically generated in the build directory
#include <insert_idle_frame_pydoc.h>

void bind_insert_idle_frame(py::module& m)
{

    using insert_idle_frame = ::gr::ccsds::insert_idle_frame;


    py::class_<insert_idle_frame,
               gr::block,
               gr::basic_block,
               std::shared_ptr<insert_idle_frame>>(
        m, "insert_idle_frame", D(insert_idle_frame))

        .def(py::init(&insert_idle_frame::make),
             py::arg("modulated_vector"),
             D(insert_idle_frame, make))


        .def("num_fillframes_added",
             &insert_idle_frame::num_fillframes_added,
             D(insert_idle_frame, num_fillframes_added))

        ;
}
